name: uarray
channels:
  - conda-forge
dependencies:
  - python=3.6
  - matchpy
  - python-graphviz
  #   - tensorflow
  - numba
  # for development
  - mypy
  - black
  - pylint
  - jupyterlab
  - flake8
  # for testing
  - numpy
  - hypothesis
  - pytest
  - ipdb
  - pudb
  - pip:
      - astunparse
