variables:
  CIBW_TEST_COMMAND: "pip install -r {project}/requirements/tests.txt && pytest --pyargs uarray"
  CIBW_BUILD: cp3?-*
  CIBW_SKIP: cp34-*

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - template: ci/azure-steps.yml
- job: MacOS
  pool:
    vmImage: 'macos-10.14'
  steps:
    - template: ci/azure-steps.yml
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - template: ci/azure-steps-windows.yml
- job: Docs_Linting_Coverage
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - template: ci/azure-doc-lint-cov.yml


trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'

pr:
- master