pool:
  vmImage: "Ubuntu 16.04"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
      architecture: "x64"

  - script: pip install flit
  - script: flit -f udispatch.toml install --symlink
  - script: flit -f uarray.toml install --symlink
  - script: flit -f umoa.toml install --symlink
  - script: flit -f umoa_parser.toml install --symlink
  - script: flit -f unumpy.toml install --symlink
  - script: flit -f uvisualize.toml install --symlink

  - script: py.test
    displayName: Run tests

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFiles: "**/test-*.xml"
      testRunTitle: "Publish test results"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/htmlcov"
