pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- script: cd uarray; python -m pip install -r requirements.txt
  displayName: Install python deps

- script: cd uarray; mypy uarray
  displayName: 'Run mypy'

- script: cd uarray; python extract_readme_tests.py
  displayName: 'extract tests from readme'

- script: cd uarray; py.test
  displayName: Run tests

- task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'