name: uarray
channels:
  - conda-forge
dependencies:
  - python=3.7
  - matchpy
  - python-graphviz
  # for development
  - mypy
  - black
  - pylint
  - jupyterlab
  # for testing
  - numpy
  - hypothesis
  - pytest
