name: uarray
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - jupyterlab
  - hypothesis
  - pytest
  - mypy
  - black
  - pylint
  # need unreleased Python 3.7 support https://github.com/HPAC/matchpy/pull/34
  - pip:
      - git+https://github.com/HPAC/matchpy.git
