[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]

[tool.black]
exclude = 'uarray/_version.py'

[tool.setuptools_scm]
write_to = "uarray/_version.py"

[tool.mypy]
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "pytest_black.*",
]
ignore_missing_imports = true
