[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "uarray"
author = "Saul Shanabrook"
author-email = "s.shanabrook@gmail.com"
home-page = "https://github.com/Quansight-Labs/uarray"
description-file = "README.md"
requires = [
    "matchpy",
    "numpy",
    "astunparse",
    "typing_extensions",
    "black"
]
classifiers=[
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
]

[tool.flit.metadata.requires-extra]
viz = [ "graphviz" ]